name: cd
on:
  create:
jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/test-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build for ref $GITHUB_REF"
          echo "test, and deploy your project."
